services:
  frontend:
    build:
      context: ./Zerohedge store
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./NodeJSDemo
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/evolvenode
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
