apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # Expose MongoDB's default port
      targetPort: 27017 # Container's port
  type: ClusterIP # Default type for internal services
